from pydantic import BaseModel, Field

class ChatRequest(BaseModel):
    query: str = Field(..., description="The user's query or prompt.", min_length=1)

class ChatResponse(BaseModel):
    success: bool = Field(..., description="Whether the request was successful.")
    response: str = Field(..., description="The response generated by the AI.")
    mode: str = Field("deep_research", description="The routing mode: casual_chat, knowledge_answer, or deep_research.")
    research_score: int = Field(0, description="The computed research score.")
    intent: str = Field("Unknown", description="The detected user intent.")
    citations: list = Field([], description="List of structured citations.")
